[phases.setup]
aptPkgs = ["...", "ffmpeg", "python3-pip"]

[phases.build]
cmds = ["...", "pip install -r requirements.txt"]

[variables]
# This manually tells the system where to look for binaries if PATH fails
PATH = "/usr/bin:/usr/local/bin:$PATH"

[start]
cmd = "python main.py"
