[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
# Use python3 specifically to avoid "executable not found"
cmds = ["python3 -m venv /app/.venv", "/app/.venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/app/.venv/bin/python3 main.py"
